import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/storeProvider";
import UserSessionProvider from "./_components/UserSessionProvider";
import { Toaster } from "sonner";
import { Header } from "./_components/header-books";
import { SidebarProvider } from "@/components/ui/sidebar";
import { CartProvider } from "./_components/cart/cart-provider";
import { Sidebar } from "./_components/side-bar";
import InnerBody from "./Body";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <StoreProvider>
          <UserSessionProvider />
          <SidebarProvider>
            <CartProvider>

              <InnerBody>
                <Sidebar />

                <div className="flex containerEdited justify-start items-center flex-col">

                  <div className=" sticky top-0 z-20  w-full">

                    <Header />

                  </div>

                  <div className="w-full containerEdited  ">


                    {children}
                  </div>
                </div>
              </InnerBody>

            </CartProvider>
          </SidebarProvider>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
