import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/storeProvider";
import UserSessionProvider from "./_comonents/UserSessionProvider";
import NavBar from "./_comonents/navBar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <UserSessionProvider />
          <div className="flex flex-col justify-center items-center">
            <div className="w-full container sm:w-[87vw]">
              <NavBar />
            </div>

            {children}
            <Toaster/>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
